apiVersion: batch/v1
kind: Job
metadata:
  name: run-job
spec:
  template:
    spec:
      containers:
      - name: run-job
        image: busybox:musl
        command: ["ls",  "-la"]
      restartPolicy: Never
  backoffLimit: 4